#!/bin/sh -e

jdiralias=java-7-oracle

case "$1" in
purge)
    if [ -z "$jdiralias" ]; then
	echo >&2 "$(basename $0): Internal error"
	exit 1
    fi
    rm -rf /etc/$jdiralias

    # XXX should remove /etc/.java ???
    ;;
esac

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_installmime
if which update-mime >/dev/null 2>&1; then update-mime; fi
# End automatically added section
# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section

