#!/bin/sh

set -e

if dpkg-maintscript-helper supports mv_conffile 2>/dev/null; then
	dpkg-maintscript-helper mv_conffile /etc/chromium-browser/default /etc/chromium/default 10.0.648.82~r75062-0 -- "$@"
	dpkg-maintscript-helper mv_conffile /etc/chromium-browser/master_preferences /etc/chromium/master_preferences 10.0.648.82~r75062-0 -- "$@"
fi

# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section

